### ISSUE TITLE
Inferring project path is broken if called from a package that wraps staticjinja

### ISSUE THREAD

**Issue by shuhaowu** [staticjinja/staticjinja#149]
I'm working on a small python package that wraps staticjinja (calls Site.render...). This package is installed via `setup.py` and I can call the package via a console entry_point.

In this configuration, staticjinja incorrectly detects the project in these lines of code: https://github.com/staticjinja/staticjinja/blob/adcf046/staticjinja/staticjinja.py#L191-L201. Specifically, calling module becomes: `<module '__main__' from '/path/to/executable/created/via/setuptools'>`.

Ideally, I would like to force jinja2 to render for cwd. A workaround could be passing the absolute path when calling the API.

Not 100% certain if this is a bug, but certainly it is a bit surprising as I expected it to render for cwd.

**Comment by NickCrews** [comment]
Hi again! I understand the concern. You are totally right, passing an absolute path would work great as a workaround.

But, I _do_ think this a behavior that should be removed. This behavior was added waaaaaay back in https://github.com/staticjinja/staticjinja/commit/d76ef6fc58951d7136b78020ff32b0e690936378 in 2012, and I think it was a mistake to do that. I have always thought that it should just use the CWD as the root, since I think (though I don't really have evidence to back this up, this is just the impression I get) this is much more of a standard. Ideally, I think staticjinja should either use an absolute path, or coerce it by assuming CWD is the root, and not doing any of this `calling_module` shenanigans. I've been trying to figure out two things:

1. What would be the use cases that would break if we did this
2. How could we add in some custom detection of these scenarios so if a user does this, they just get a deprecation warning at first, before the change is final.

I'm playing around and coming up with some test cases now, and seeing what will mitigate the breakage. If it's not too much hassle do you think you could share your exact code with me? I could write up some setuptools entrypoint stuff too, but it would probably save me some time.

I'll link any PRs I come up with here, anyone's thoughts on any of this would be appreciate. If anyone actually sees this it might be nice to just get some sort of emoji reaction here so I know that at least people are aware of this change...

**Comment by NickCrews** [comment]
@shuhaowu, I deprecated this behavior in #150, if you have any thoughts or feedback on that resolution I'd love to hear them!
