### ISSUE TITLE
Partial & Ignored files not detected on Windows

### ISSUE THREAD

**Issue by fasih** [staticjinja/staticjinja#88]
Firstly I would like to say that, all piece of code is already platform-agnostic. 

So there are most likely minimum changes of issues on different platforms (notably Windows)

But I found an interesting thing since we are using `FileSystemLoader` from jinja2 loaders.
These is a method called `.list_templates` in  `FileSystemLoader `  below

```
    def list_templates(self):
         ---
         ---
                for filename in filenames:
                    template = (
                        os.path.join(dirpath, filename)[len(searchpath) :]
                        .strip(os.path.sep)
                        .replace(os.path.sep, "/")
                    )
         ---
         ---
        return sorted(found)
```
which replaces `os.path.sep` with "/" (forward slash). 

And we have two methods `is_partial` and `is_ignored` which sometimes takes jinja2 template name (indirectly while passing `filter_func`) and sometimes take relative os file path name (in reloader while watching `event_handler`)

Hence I am suggesting a change for actual cross-platform support.

**Comment by NickCrews** [comment]
Hey @fasihahmad, thanks for the issue! I see what you're saying, this should get unified.

Thanks for the PR in #89. However, my first thought is that we should follow the jinja2 convention, and always use `/`. When `is_partial` and similar are used by jinja2's `filter_func`, they will only receive paths using `/`. Actually, this makes me realize that the argument for `is_partial` should be changed from `filename` to `template_name` to emphasize this. So actually I think #89 can be simplified even further, and just change the `filename.split(os.path.sep)` to `template_name.split("/")`. This would require that the reloader code be changed to convert the filename (sometimes windows, sometimes posix) to a template path (always posix).

However, this whole thing is kinda confusing wrapping my head around, so if you have counterexamples that would be useful.

**Comment by fasihahmad** [comment]
Hi @NickCrews , thanks for the review.
You are absolutely right. If we restrict the responsibility of our `filter_func`  
(`is_ignored`, `is_partial`) only for jinja2 then it make more sense to even 
change the name of the parameter. 

But I think these `filter_func` are designed to share responsibilities (while I don't like)

1. Handle jinja2 style template name (while passing in jinja2 `env.list_templates`)
2. Handle os based filesystem name (while using `get_dependencies` only in reloader)

Because these are being tested out from filesystem mindset too.
```
def test_ignored_file_in_nested_directory_is_ignored(site):
    assert site.is_ignored(os.sep.join(['foo', '.bar', 'index.html']))
```

Adding more test cases for clearing context and reverting my changes to see results.

**Comment by fasihahmad** [comment]
Now build will fail only for windows [#141](https://travis-ci.org/github/Ceasar/staticjinja/builds/694224505)
See updated test cases at #89

**Comment by fasihahmad** [comment]
Final changes at #89 :
 1. Have a consistent `filter_func` for posix style template name using `filename.split("/")`
2. Updated `get_dependencies` (designed to be used by reloader only)
3. Updated `filter_func ` related test cases (replaced `os.sep.join` with `'/'.join`
4. Not updated parameter name because, used loader is a `FileSystemLoader` so this even make sense to have parameter name as filename

**Comment by NickCrews** [comment]
I merged these changes in https://github.com/staticjinja/staticjinja/pull/104
